application.data-dir: D:/SAMPAH
spring:
  datasource:
    url: jdbc:${DB_PROTO:mysql}://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:springboot}
    username: ${DB_USER:root}
    password: ${DB_PASS:}
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.${DB_DIALECT:MariaDB103Dialect}
  messages.basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB